### PR TITLE
Adding RealGithub Theme

### PR DESCRIPTION
**Pull request by NoHomey**
Adding theme which purpose is to be exact copy of the theme used by github.

### CODE REVIEW

**Comment by aziz** [comment]
Your theme is invalid by the way. you have an extra hex color in the beginning of the file 
`#ED6A43<?xml version="1.0" encoding="UTF-8"?>` fix it and you'll be able to see it live in the editor

**Comment by NoHomey** [comment]
Real thanks, it's fixed now.

**Comment by NoHomey** [comment]
I made some theme changes, can you deploy once more because I've added an edit link at (https://github.com/RealGithub/RealGithub#pull-request ) and I want changes to be visible ?

**Comment by aziz** [comment]
I don't need to do anything. as long as the url is the same everything is fine. you might need to clear the editor's cache for force it get the new content. 

screen shot 2016-06-26 at 10 48 13 pm

**Pull request merged**
